### PR TITLE
Feat: added scroll on nav item click

### PR DESCRIPTION
**Pull request by Akalanka47000**

### CODE REVIEW

**Review by miyurugunarathna — CHANGES_REQUESTED** [review]
Shall we add this to logo as well?

**Comment by Akalanka47000** [comment]
> Shall we add this to logo as well?

Scroll to the very top on click ?

**Comment by miyurugunarathna** [comment]
> > Shall we add this to logo as well?
> 
> Scroll to the very top on click ?

yes

**Comment by Akalanka47000** [comment]
> > > Shall we add this to logo as well?
> > 
> > 
> > Scroll to the very top on click ?
> 
> yes

Okay

**Review by miyurugunarathna — APPROVED** [review]

**Pull request merged**
